// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubHiP6Xv7pCwMgG-zVoiSsXD82HZeesM',
    appId: '1:427131704676:web:eda8a9fc408927a9ef5671',
    messagingSenderId: '427131704676',
    projectId: 'expensetracker-c5f59',
    authDomain: 'expensetracker-c5f59.firebaseapp.com',
    storageBucket: 'expensetracker-c5f59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGK2ENqNg4Y-M7liHfTDzy-TGIshP58M',
    appId: '1:427131704676:android:7227e5e7d1e0166fef5671',
    messagingSenderId: '427131704676',
    projectId: 'expensetracker-c5f59',
    storageBucket: 'expensetracker-c5f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2yFZZdlut544vHrI-NpjmfoxmPNjFXCQ',
    appId: '1:427131704676:ios:226163d89f75fca3ef5671',
    messagingSenderId: '427131704676',
    projectId: 'expensetracker-c5f59',
    storageBucket: 'expensetracker-c5f59.firebasestorage.app',
    iosClientId: '427131704676-r545hf0f0nkh64fc0jr91s8gigi8vfi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2yFZZdlut544vHrI-NpjmfoxmPNjFXCQ',
    appId: '1:427131704676:ios:226163d89f75fca3ef5671',
    messagingSenderId: '427131704676',
    projectId: 'expensetracker-c5f59',
    storageBucket: 'expensetracker-c5f59.firebasestorage.app',
    iosClientId: '427131704676-r545hf0f0nkh64fc0jr91s8gigi8vfi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDubHiP6Xv7pCwMgG-zVoiSsXD82HZeesM',
    appId: '1:427131704676:web:c65616b2523f5aebef5671',
    messagingSenderId: '427131704676',
    projectId: 'expensetracker-c5f59',
    authDomain: 'expensetracker-c5f59.firebaseapp.com',
    storageBucket: 'expensetracker-c5f59.firebasestorage.app',
  );

}